version: '3.5'

services:
  ambassador:
    image: quay.io/datawire/ambassador:0.38.0
    ports:
    # expose port 80 via 8080 on the host machine
    - 8080:80
    volumes:
    # mount a volume where we can inject configuration files
    - ./config:/ambassador/ambassador-config


