// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mailer.proto

package mailer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WelcomeMailRequest struct {
	Details              *User    `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WelcomeMailRequest) Reset()         { *m = WelcomeMailRequest{} }
func (m *WelcomeMailRequest) String() string { return proto.CompactTextString(m) }
func (*WelcomeMailRequest) ProtoMessage()    {}
func (*WelcomeMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eced95006893a4c, []int{0}
}

func (m *WelcomeMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeMailRequest.Unmarshal(m, b)
}
func (m *WelcomeMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeMailRequest.Marshal(b, m, deterministic)
}
func (m *WelcomeMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMailRequest.Merge(m, src)
}
func (m *WelcomeMailRequest) XXX_Size() int {
	return xxx_messageInfo_WelcomeMailRequest.Size(m)
}
func (m *WelcomeMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMailRequest proto.InternalMessageInfo

func (m *WelcomeMailRequest) GetDetails() *User {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *WelcomeMailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WelcomeMailRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eced95006893a4c, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Response struct {
	SendSuccess          bool                 `protobuf:"varint,1,opt,name=sendSuccess,proto3" json:"sendSuccess,omitempty"`
	SentAt               *timestamp.Timestamp `protobuf:"bytes,2,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	Errors               []*Error             `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eced95006893a4c, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSendSuccess() bool {
	if m != nil {
		return m.SendSuccess
	}
	return false
}

func (m *Response) GetSentAt() *timestamp.Timestamp {
	if m != nil {
		return m.SentAt
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eced95006893a4c, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*WelcomeMailRequest)(nil), "mailer.WelcomeMailRequest")
	proto.RegisterType((*User)(nil), "mailer.User")
	proto.RegisterType((*Response)(nil), "mailer.Response")
	proto.RegisterType((*Error)(nil), "mailer.Error")
}

func init() { proto.RegisterFile("mailer.proto", fileDescriptor_5eced95006893a4c) }

var fileDescriptor_5eced95006893a4c = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xad, 0x5b, 0xeb, 0xfa, 0x76, 0x43, 0x09, 0x1e, 0x4a, 0x11, 0x2c, 0x05, 0xa5, 0xa7,
	0x0e, 0xea, 0xd9, 0xc3, 0x0e, 0x1e, 0xe7, 0x21, 0xf3, 0xcf, 0xb9, 0x6b, 0xdf, 0x8d, 0x60, 0xdb,
	0xd4, 0x24, 0x13, 0xfc, 0x04, 0x7e, 0x6d, 0x49, 0xd2, 0xcc, 0x81, 0xb7, 0x3c, 0xcf, 0x13, 0x7e,
	0x6f, 0xde, 0x27, 0x30, 0xef, 0x2a, 0xd6, 0xa2, 0x28, 0x06, 0xc1, 0x15, 0x27, 0x81, 0x55, 0xc9,
	0xed, 0x9e, 0xf3, 0x7d, 0x8b, 0x4b, 0xe3, 0x6e, 0x0f, 0xbb, 0xa5, 0x62, 0x1d, 0x4a, 0x55, 0x75,
	0x83, 0xbd, 0x98, 0xf5, 0x40, 0xde, 0xb1, 0xad, 0x79, 0x87, 0xeb, 0x8a, 0xb5, 0x14, 0x3f, 0x0f,
	0x28, 0x15, 0xb9, 0x87, 0x8b, 0x06, 0x55, 0xc5, 0x5a, 0x19, 0x7b, 0xa9, 0x97, 0x47, 0xe5, 0xbc,
	0x18, 0xf1, 0xaf, 0x12, 0x05, 0x75, 0x21, 0xb9, 0x06, 0x5f, 0xf1, 0x0f, 0xec, 0xe3, 0xf3, 0xd4,
	0xcb, 0x43, 0x6a, 0x05, 0x49, 0x60, 0x36, 0x08, 0xc6, 0x05, 0x53, 0xdf, 0xf1, 0x24, 0xf5, 0x72,
	0x9f, 0x1e, 0x75, 0xf6, 0x06, 0x53, 0x8d, 0x20, 0x37, 0x10, 0xee, 0x98, 0x90, 0xea, 0xb9, 0xea,
	0xd0, 0xcc, 0x08, 0xe9, 0x9f, 0xa1, 0x09, 0x6d, 0x35, 0x86, 0x16, 0x7d, 0xd4, 0x7a, 0x26, 0xea,
	0xc7, 0x18, 0x74, 0x48, 0xad, 0xc8, 0x7e, 0x3c, 0x98, 0x51, 0x94, 0x03, 0xef, 0x25, 0x92, 0x14,
	0x22, 0x89, 0x7d, 0xb3, 0x39, 0xd4, 0x35, 0x4a, 0xbb, 0xc2, 0x8c, 0x9e, 0x5a, 0xa4, 0x84, 0x40,
	0x62, 0xaf, 0x56, 0xca, 0xe0, 0xa3, 0x32, 0x29, 0x6c, 0x51, 0x85, 0x2b, 0xaa, 0x78, 0x71, 0x45,
	0xd1, 0xf1, 0x26, 0xb9, 0x83, 0x00, 0x85, 0xe0, 0x42, 0xc6, 0x93, 0x74, 0x92, 0x47, 0xe5, 0xc2,
	0x75, 0xf2, 0xa4, 0x5d, 0x3a, 0x86, 0xd9, 0x23, 0xf8, 0xc6, 0x20, 0x04, 0xa6, 0x35, 0x6f, 0xec,
	0x76, 0x3e, 0x35, 0x67, 0xfd, 0xb2, 0x06, 0x65, 0x2d, 0xd8, 0xa0, 0x18, 0x77, 0xb5, 0x9d, 0x5a,
	0x25, 0x85, 0xc5, 0xda, 0x60, 0x37, 0x28, 0xbe, 0x58, 0x8d, 0x64, 0x05, 0x97, 0x1b, 0xec, 0x9b,
	0x93, 0x5f, 0x22, 0x89, 0x9b, 0xfc, 0xff, 0xeb, 0x92, 0x2b, 0x97, 0xb9, 0x36, 0xb2, 0xb3, 0x6d,
	0x60, 0xb6, 0x7a, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x81, 0x31, 0x8c, 0x24, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailerServiceClient is the client API for MailerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailerServiceClient interface {
	SendWelcomeMail(ctx context.Context, in *WelcomeMailRequest, opts ...grpc.CallOption) (*Response, error)
}

type mailerServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailerServiceClient(cc *grpc.ClientConn) MailerServiceClient {
	return &mailerServiceClient{cc}
}

func (c *mailerServiceClient) SendWelcomeMail(ctx context.Context, in *WelcomeMailRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mailer.MailerService/SendWelcomeMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailerServiceServer is the server API for MailerService service.
type MailerServiceServer interface {
	SendWelcomeMail(context.Context, *WelcomeMailRequest) (*Response, error)
}

func RegisterMailerServiceServer(s *grpc.Server, srv MailerServiceServer) {
	s.RegisterService(&_MailerService_serviceDesc, srv)
}

func _MailerService_SendWelcomeMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServiceServer).SendWelcomeMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailer.MailerService/SendWelcomeMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServiceServer).SendWelcomeMail(ctx, req.(*WelcomeMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mailer.MailerService",
	HandlerType: (*MailerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWelcomeMail",
			Handler:    _MailerService_SendWelcomeMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mailer.proto",
}
